trigger:
  batch: true
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

stages:

# Lint the Bicep file.
- stage: Lint
  jobs: 
  - template: pipeline-templates/lint.yml

# Deploy to the test environment.
- template: pipeline-templates/deploy.yml
  parameters:
    environmentType: ToyWebsiteTestEnv
    resourceGroupName: ToyWebsiteTest
    serviceConnectionName: ToyWebsiteTestEnv

# Deploy to the production environment.
- template: pipeline-templates/deploy.yml
  parameters:
    environmentType: ToyWebsiteProdEnv
    resourceGroupName: ToWebsiteProduction
    serviceConnectionName: ToyWebsiteProdEnv